name: umami_tracker
description: A Umami tracker for Flutter that allows you to track screen views and events.
version: 0.2.0
homepage: https://davidserrano.io

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  devicelocale: ^0.8.1
  dio: ^5.8.0+1
  fk_user_agent:
    git:
      url: https://github.com/tarzanking/fk_user_agent
      ref: 2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2
  mocktail: ^0.3.0

flutter: